#!/bin/sh

if nginx -V 2>&1 | grep -q ubus; then
	if [ -z "$(cat /etc/nginx/conf.d/luci.locations | grep ubus)" ]; then
		cat <<EOT >> /etc/nginx/conf.d/luci.locations

location /ubus {
        ubus_interpreter;
        ubus_socket_path /var/run/ubus/ubus.sock;
        ubus_parallel_req 2;
}
EOT
	fi
fi

grep -q /var/run/ubus.sock /etc/nginx/conf.d/luci.locations &&
	sed -i 's#/var/run/ubus.sock#/var/run/ubus/ubus.sock#' /etc/nginx/conf.d/luci.locations

if [ -x /etc/init.d/uhttpd ]; then
        /etc/init.d/uhttpd enable
        if [ -n "$(pgrep uhttpd)" ]; then
                /etc/init.d/uhttpd start
        fi
fi

/etc/init.d/nginx disable
/etc/init.d/nginx stop

/etc/init.d/uwsgi enable
if [ -n "$(pgrep uwsgi)" ]; then
        /etc/init.d/uwsgi restart
else
        /etc/init.d/uwsgi start
fi


exit 0
